export const allProjects = [
  {
    id: 1,
    title: "House Management System",
    description:
      "Comprehensive system for managing residential properties and rentals.",
    category: "Management Systems",
    image: "/m-systems/house-management-system.png",
    technologies: [
      "React",
      "JavaScript",
      "TypeScript",
      "Express.js",
      "Shadcn",
      "Tailwind CSS",
      "Turso",
    ],
    liveUrl: "#",
    githubUrl: "#",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: 7,
    title: "Broad Services Portfolio",
    description:
      "Portfolio highlighting a wide range of professional services.",
    category: "Websites",
    image: "/Portfolios/Broad_Portfolio.png",
    technologies: [
      "React",
      "Tailwind CSS",
      "TypeScript",
      "JavaScript",
      "Shadcn",
    ],
    liveUrl: "https://www.harrytechservices.com/",
    githubUrl: "#",
    gradient: "from-teal-500 to-cyan-500",
  },
  {
    id: 2,
    title: "E-commerce Clothes Website",
    description:
      "Online store specializing in clothing and apparel with secure checkout.",
    category: "Websites",
    image: "/websites_thumbnail/ecommerce.png",
    technologies: ["React", "JavaScript", "Express.js", "Supabase"],
    liveUrl: "https://patos-front-end-hcke.vercel.app/",
    githubUrl: "#",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    title: "Beauty Services Website",
    description:
      "Platform for hair styling, manicure, and pedicure services with booking features.",
    category: "Websites",
    image: "/websites_thumbnail/beauty2.png",
    technologies: ["Next.js", "React", "JavaScript"],
    liveUrl: "https://beauty-live-website.vercel.app/",
    githubUrl: "#",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: 4,
    title: "WiFi Services Website",
    description:
      "Site offering internet and WiFi services with plan comparisons and sign-ups.",
    category: "Websites",
    image: "/websites_thumbnail/wifi.png",
    technologies: ["Next.js", "React", "JavaScript"],
    liveUrl: "https://wifi-servicesnextjs.vercel.app/",
    githubUrl: "#",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: 5,
    title: "Bakery Website",
    description:
      "Online showcase for a bakery featuring cakes, bread, and ordering options.",
    category: "Websites",
    image: "/websites_thumbnail/Bakery.png",
    technologies: ["React", "Tailwind CSS", "TypeScript", "JavaScript"],
    liveUrl: "#",
    githubUrl: "#",
    gradient: "from-yellow-500 to-amber-500",
  },
  {
    id: 6,
    title: "Simple Personal Portfolio",
    description: "Minimalist website showcasing personal projects and skills.",
    category: "Websites",
    image: "/websites_thumbnail/harrytech.png",
    technologies: ["React", "JavaScript"],
    liveUrl: "#",
    githubUrl: "#",
    gradient: "from-indigo-500 to-violet-500",
  },

  {
    id: 8,
    title: "Marketing Portfolio",
    description: "Showcase of marketing projects, campaigns, and strategies.",
    category: "Websites",
    image: "/Portfolios/marketing_portfolio.png",
    technologies: [
      "React",
      "Tailwind CSS",
      "TypeScript",
      "JavaScript",
      "Shadcn",
    ],
    liveUrl: "#",
    githubUrl: "#",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: 9,
    title: "Real Estate Website",
    description:
      "Platform for property listings, searches, and real estate management.",
    category: "Websites",
    image: "/websites_thumbnail/real-estate.png",
    technologies: ["React", "JavaScript", "Next.js"],
    liveUrl: "https://real-estate-nextjs-one-sigma.vercel.app/",
    githubUrl: "#",
    gradient: "from-gray-500 to-slate-500",
  },
];
